[package]
name = "g3keymess-ctl"
version = "0.1.0"
license.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
clap.workspace = true
tokio = { workspace = true, features = ["rt", "macros", "io-util", "fs"] }
futures-util.workspace = true
capnp.workspace = true
hex.workspace = true
openssl.workspace = true
g3-ctl.workspace = true
g3-tls-cert.workspace = true
g3keymess-proto = { path = "../../proto" }
