[package]
name = "g3proxy-lua"
version = "0.1.0"
license.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
clap.workspace = true
clap_complete.workspace = true
mlua = { workspace = true, optional = true }

[features]
default = ["lua54"]
lua = ["mlua"]
luajit = ["lua", "mlua/luajit"]
lua51 = ["lua", "mlua/lua51"]
lua53 = ["lua", "mlua/lua53"]
lua54 = ["lua", "mlua/lua54"]

[[bin]]
name = "g3proxy-lua"
required-features = ["lua"]
