[package]
name = "g3tiles"
version = "0.2.4"
license.workspace = true
edition.workspace = true
description = "G3 generic reverse proxy"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
async-trait.workspace = true
yaml-rust.workspace = true
log = { workspace = true, features = ["max_level_trace", "release_max_level_info"] }
once_cell.workspace = true
rand.workspace = true
clap.workspace = true
clap_complete.workspace = true
indexmap.workspace = true
arc-swap.workspace = true
cadence.workspace = true
ahash.workspace = true
itoa.workspace = true
ascii.workspace = true
slog = { workspace = true, features = ["nested-values", "max_level_trace", "release_max_level_info"] }
capnp.workspace = true
capnp-rpc.workspace = true
tokio = { workspace = true, features = ["net", "sync", "time"] }
openssl.workspace = true
tokio-openssl.workspace = true
rustls.workspace = true
tokio-rustls.workspace = true
rustls-native-certs.workspace = true
governor = { workspace = true, features = ["std", "jitter"] }
chrono = { workspace = true, features = ["clock"] }
uuid = { workspace = true, features = ["v1", "v4"] }
g3-compat.workspace = true
g3-daemon.workspace = true
g3-signal.workspace = true
g3-yaml = { workspace = true, features = ["acl-rule", "route", "openssl", "rustls"] }
g3-types = { workspace = true, features = ["acl-rule", "route", "openssl", "rustls"] }
g3-socket.workspace = true
g3-io-ext.workspace = true
g3-statsd.workspace = true
g3tiles-proto = { path = "proto" }

[build-dependencies]
rustc_version = "0.4"

[features]
default = []
vendored-openssl = ["openssl/vendored"]
