[package]
name = "g3bench"
version = "0.6.2"
license.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror.workspace = true
anyhow.workspace = true
clap.workspace = true
clap_complete.workspace = true
async-trait.workspace = true
indicatif = "0.17"
is-terminal = "0.4"
tokio = { workspace = true, features = ["rt", "net", "macros"] }
http.workspace = true
url.workspace = true
h2.workspace = true
bytes.workspace = true
futures-util.workspace = true
tokio-openssl.workspace = true
openssl.workspace = true
openssl-probe = { workspace = true, optional = true }
cadence.workspace = true
hdrhistogram = { version = "7.5", default-features = false, features = ["sync"] }
ahash.workspace = true
fxhash.workspace = true
concurrent-queue = "2.2"
hex.workspace = true
g3-runtime.workspace = true
g3-signal.workspace = true
g3-types = { workspace = true, features = ["proxy"] }
g3-clap.workspace = true
g3-socket.workspace = true
g3-http.workspace = true
g3-socks.workspace = true
g3-io-ext.workspace = true
g3-statsd.workspace = true
g3-tls-cert.workspace = true

[build-dependencies]
rustc_version = "0.4"

[features]
default = []
vendored-openssl = ["openssl/vendored", "dep:openssl-probe"]
