[package]
name = "g3bench"
version = "0.8.5"
license.workspace = true
edition.workspace = true
rust-version = "1.70.0"
description = "G3 Benchmark Tool"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror.workspace = true
anyhow.workspace = true
clap.workspace = true
clap_complete.workspace = true
async-trait.workspace = true
indicatif = "0.17"
tokio = { workspace = true, features = ["rt", "net", "macros"] }
http.workspace = true
url.workspace = true
h2.workspace = true
h3.workspace = true
h3-quinn.workspace = true
quinn = { workspace = true, features = ["tls-rustls", "runtime-tokio"] }
bytes.workspace = true
futures-util.workspace = true
atomic-waker.workspace = true
tokio-openssl.workspace = true
openssl.workspace = true
openssl-probe = { workspace = true, optional = true }
rustls.workspace = true
rustls-pemfile.workspace = true
cadence.workspace = true
hdrhistogram.workspace = true
ahash.workspace = true
rustc-hash.workspace = true
concurrent-queue = "2.2"
hex.workspace = true
hickory-client = { workspace = true, features = ["dns-over-rustls", "dns-over-https-rustls", "dns-over-quic", "native-certs"] }
hickory-proto = { workspace = true, features = ["dns-over-h3"] }
g3-runtime = { workspace = true, features = ["openssl"] }
g3-signal.workspace = true
g3-types = { workspace = true, features = ["proxy", "openssl", "rustls"] }
g3-clap.workspace = true
g3-socket.workspace = true
g3-http.workspace = true
g3-socks = { workspace = true, features = ["quic"] }
g3-io-ext = { workspace = true, features = ["quic"] }
g3-statsd.workspace = true
g3-histogram.workspace = true
g3-tls-cert.workspace = true
openssl-async-job.workspace = true

[build-dependencies]
rustc_version.workspace = true

[features]
default = []
vendored-openssl = ["openssl/vendored", "dep:openssl-probe"]
vendored-tongsuo = ["openssl/tongsuo", "dep:openssl-probe", "g3-types/vendored-tongsuo"]
