[package]
name = "g3proxy-proto"
version = "0.1.0"
license.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
capnp.workspace = true

[build-dependencies]
capnpc.workspace = true
